config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :index, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages

  accepts_nested_attributes_for :group_users, allow_destroy: true

  validates :name, presence: true

  # after_create :create_group_user

  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end

  # private
  # def create_group_user
  #   self.group_user = GroupUser.create(group_id: group_id, user_id: current_user.id, updated_at: updated_at)
  # end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?
  validates :group, :user, presence: true

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # deviseでは初期状態でサインアップ時にメールアドレスとパスワードのみを受け取れるようにストロングパラメーターが設定してあるので、追加したキーは許可されていない。
  # ユーザーの名前のようなdeviseのデフォルトで設定されているカラム以外のデータを保存する場合は設定を追加しないといけない。
  # 追加のパラメーターを許可したい時は、application_controller.rbにおいてbefore_actionにconfigure_permitted_parametersメソッドを設定する。
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]
  # グループの情報呼び出す処理はset_groupメソッドにまとめ、before_actionで呼び出す。

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end
  # @group.users << current_userと記述することで、現在ログイン中のユーザーを新規作成したグループに追加している。


  def create
    @group = Group.new(group_params)
    GroupUser.create(group_user_params)
    if @group.save
      redirect_to root_path, notice:'グループを作成しました'
    else
      flash.now[:alert] = "グループ名を入力してください"
      render :new
    end
  end
  # renderはHTTPリクエストを送らず、該当するビューだけを表示する。
  # redirect_toだとHTTPリクエストを送りそのレスポンスとして返ってくるビューを表示する。


  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path, notice: 'グループを編集しました'
    else
      render :edit
    end
  end
  # グループが編集された時更新の可否に合わせた処理ができるように記述する。

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def group_user_params
    # params.require(:group).permit()
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    @new_messages = @messages.where('id > ?', params[:message])
    respond_to do |format|
      format.html
      # format.json { @new_messages = Message.where('id > ?', params[:message]) }
      format.json
    end
  end


  # def create
  #   @message = @group.messages.new(message_params)
  #   if @message.save
  #     redirect_to group_messages_path(@group), notice: 'メッセージが送信されました'
  #   else
  #     @messages = @group.messages.includes(:user)
  #     flash.now[:alert] = 'メッセージを入力してください。'
  #     render :index
  #   end
  # end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group),flash: { notice: "送信しました"} }
        format.json
      end
    else
      @message = @group.message.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください'
      render :index
    end
  end

  # def create
  #   @message = @group.messages.new(message_params)
  #   if @message.save
  #     respond_to do |format|
  #       format.json
  #     end
  #   else
  #     @messages = @group.messages.includes(:user)
  #     flash.now[:alert] = 'メッセージを入力してください'
  #     render :index
  #   end
  # end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where.not(id: params[:users_id]).where('name LIKE(?)', "#{params[:keyword]}%")
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    @users = User.where.not(id: params[:users_id]).where('name LIKE(?)', "#{params[:keyword]}%")
    if current_user.update(user_params)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json
      end
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "group_チャットメンバーを追加"}
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", name: "keyword", :type => "text"}/
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right

      #chat-group-users
        #chat-group-user-22.chat-group-user.clearfix
          %input{:name => "group[user_ids][]", :type => "hidden", :value => "#{current_user.id}"}/
          %p.chat-group-user__name
            = current_user.name

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field-right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper.flexbox


  = render 'shared/side_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key


/ flashとは？
/ ログイン時のウェルカムメッセージや、項目追加の成功通知など、ユーザーに簡単な通知を行いたいときに利用する。
/ コントローラーでflashメッセージを設定し、ビューで表示する。
/ flashは全体で見ればhash。あるキーに対する値としてメッセージを設定する。キーは自由に設定できるが、デフォルトとしてalertとnoticeがある。
/ 設定したメッセージはsessionに保存される。つまりflashはsessionを利用した機能の１つ。
/ 普通のセッション変数では破棄するまで値は保持されるが、flashの場合は一度表示されるとアクション終了時に自動的に消去される。

/ 使い方
/ コントローラーで定義
/ flash[:notie] = "hogehoge"
/ redirect_toのオプションとしても追加できる。
/ redirect_to :root, flash => {:error => "errorが起きました"}
/ ビューで表示
/ <%= flash[:alert]%>

/ flashの種類
/ flash
/ 一度表示されるまで値が保持される。
/ そのアクション自体か、リダイレクトした次のアクションで利用。
/ 一度表示された時点では記される。
/ flash.now
/ 定義したメソッド内(同じリクエスト内)でのみ有効。
/ メソッド１で定義した場合、メソッド２では利用不可。
/ redirectさせた先では表示されない。

/ 使い方
/ コントローラー
/ flash.now[:notice] = "hello"
/ ビュー
/ <%= flash[:notice] %>

app/views/layouts/_notificationshtml.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key


/ flashとは？
/ ログイン時のウェルカムメッセージや、項目追加の成功通知など、ユーザーに簡単な通知を行いたいときに利用する。
/ コントローラーでflashメッセージを設定し、ビューで表示する。
/ flashは全体で見ればhash。あるキーに対する値としてメッセージを設定する。キーは自由に設定できるが、デフォルトとしてalertとnoticeがある。
/ 設定したメッセージはsessionに保存される。つまりflashはsessionを利用した機能の１つ。
/ 普通のセッション変数では破棄するまで値は保持されるが、flashの場合は一度表示されるとアクション終了時に自動的に消去される。

/ 使い方
/ コントローラーで定義
/ flash[:notie] = "hogehoge"
/ redirect_toのオプションとしても追加できる。
/ redirect_to :root, flash => {:error => "errorが起きました"}
/ ビューで表示
/ <%= flash[:alert]%>

/ flashの種類
/ flash
/ 一度表示されるまで値が保持される。
/ そのアクション自体か、リダイレクトした次のアクションで利用。
/ 一度表示された時点では記される。
/ flash.now
/ 定義したメソッド内(同じリクエスト内)でのみ有効。
/ メソッド１で定義した場合、メソッド２では利用不可。
/ redirectさせた先では表示されない。

/ 使い方
/ コントローラー
/ flash.now[:notice] = "hello"
/ ビュー
/ <%= flash[:notice] %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace2
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.3.1/css/all.css", :integrity => "sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU", :rel => "stylesheet"}/

  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_message.html.haml
.message{id: "#{message.id}"}
  .upper-message
    .upper-message__user-name
      = message.user.name
    .upper-message__date
      = message.created_at
  .lower-meesage
    - if message.content.present?
      %p.lower-message__content
        = message.content
    = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/index.html.haml
.wrapper.flexbox

  = render 'shared/side_bar'

  .chat
    .header
      .left-header
        .left-header__title
          = @group.name
        %ul.left-header__members
          Member:
          - @group.users.each do |user|
            %li.member
            = user.name
      .right-header
        .right-header__button
          = link_to "Edit", edit_group_path(@group.id)
    .messages

      = render @messages

    .form
      = form_for [@group, @message], id: "new_message" do |f|
        = f.text_field :content, class: 'form__message', placeholder: 'type a message'
        .form__mask
          = f.label :image, class: 'form__mask__image' do
            ファイル
            = fa_icon 'picture-o', class: 'icon'
            = f.file_field :image, class: 'hidden'
        = f.submit 'Send', class: 'form__submit'

        / ネストされたモデルに対してform_forを使用する場合、親モデルのインスタンス(もしくは親モデルのid)を第一引数、子モデルのインスタンスを第二引数に設定する。

app/views/shared/_side_bar.html.haml
.side-bar
  .header
    %h3.header__name
      = current_user.name
    %ul.header__lists
      %li.list
      = link_to "グループ作成", new_group_path
      / = link_to new_group_path do
      /   = fa_icon 'pencil-square-o', class: 'icon'
      %li.list
      = link_to "ユーザー情報編集", edit_user_path(current_user)
      / = link_to edit_user_path(current_user) do
      /   = fa_icon 'cog', class: 'icon'
  .groups
    .group
      - current_user.groups.each do |group|
        = link_to group_messages_path(group) do
          .group__name
            = group.name
          %div{:class => "group__message", :id => "#{group.id}"}
            = group.show_last_message
            %br
            %br

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'
/ = link_toでoptionsハッシュの代わりに:backというシンボルを渡すと、リファラへのリンクを生成